stages:
  - build 
  - deploy

cache:
  paths:
    - coder-gate-ui/node_modules/

build-frontend:
  stage: build
  image: node:latest
  script:
    - cd coder-gate-ui
    - npm install
    - ng build --configuration=production
  artifacts:
    paths:
      - coder-gate-ui/dist
  tags:
    - Group19Runner

deploy-frontend:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh-client
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir -p /var/www/html/my-angular-app"
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" $Distribution "${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/html/my-angular-app/"
    - ssh -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${DEPLOY_USER}@${DEPLOY_HOST} "sudo service apache2 restart"
  tags:
    - Group19Runner
  only:
    - dev

    
