stages:
  - test
  - code-Quality
  - codeQualityOnMerge
  - build

include:
  - template: Code-Quality.gitlab-ci.yml

test:
  stage: test
  image: maven:latest
  artifacts: 
    paths:
      - coder-gate/target
    reports:
      junit:
        - ./coder-gate/target/ProjectReports/TEST_*.xml
  script:
    - cd coder-gate
    - echo "Pipeline test started"
    - mvn verify
  tags:
    - Group19Runner
  only:
    - testCICodeQuality  

code_quality:
  stage: code-Quality
  artifacts:
    paths: [gl-code-quality-report.json] 
  tags:
    - Group19Runner

code_quality_report:
  stage: codeQualityOnMerge
  image: registry.gitlab.com/gitlab-org/security-products/codequality:latest
  allow_failure: true
  rules:
    - if: '$CI_MERGE_REQUEST_IID'
      when: always
  script:
    - codeclimate analyze -f json > gl-code-quality-report.json
  artifacts:
    paths:
      - gl-code-quality-report.json

build:
  stage: build
  image: maven:latest
  script:
    - cd coder-gate
    - echo "Building the pipeline"
    - mvn clean package
  artifacts:
    paths:
      - coder-gate/target
  tags:
    - Group19Runner
  only:
    - testCICodeQuality
