image: maven:latest

stages:
  - test
  - Code-Quality
  - build

include:
  - template: Code-Quality.gitlab-ci.yml


test:
  stage: test
  artifacts:
    paths:
      - coder-gate/target
    reports:
      junit:
        - coder-gate/target/ProjectReports/TEST_*.xml
  script:
    - cd coder-gate
    - echo "Pipeline test started"
    - mvn verify
  tags:
    - Group19Runner


code_quality:
  stage: Code-Quality
  script:
    - echo "Running code quality checks" 
  artifacts:
    paths:
      - /home/gitlab-runner/builds/ju9h8FbR/0/courses/2023-winter/csci-5308/group19/coder-gate/target/gl-code-quality-report.json
  tags:
    - Group19Runner  

build:
  stage: build
  script:
    - cd coder-gate
    - echo "Building the pipeline"
    - mvn clean package
  artifacts:
    paths:
      - coder-gate/target
  tags:
    - Group19Runner




