stages:
  - build 
  - deploy

cache:
  paths:
    - coder-gate-ui/node_modules/

build-frontend:
  stage: build
  image: node:latest
  script:
    - cd coder-gate-ui
    - npm install
    - ng build --configuration=production
  artifacts:
    paths:
      - coder-gate-ui/dist
  tags:
    - Group19Runner

deploy-frontend:
  stage: deploy
  image: alpine
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "sudo -S sh -c 'mkdir -p /var/www/html/my-angular-app'" < <(echo ${SUDO_PASSWORD})
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "sudo -S sh -c 'rm -f /var/www/html/index.html'" < <(echo ${SUDO_PASSWORD})
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${Distribution} "${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/html/my-angular-app/" < <(echo ${SUDO_PASSWORD})
    - ssh -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${DEPLOY_USER}@${DEPLOY_HOST} "sudo -S sh -c 'sudo service apache2 restart'" < <(echo ${SUDO_PASSWORD})
  tags:
    - Group19Runner
  only:
    - dev

    
