stages:
  - code-Quality
  - test
  - build

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: code-Quality
  artifacts:
    paths: [gl-code-quality-report.json] 
  tags:
    - Group19Runner

test:
  stage: test
  image: maven:latest
  script:
    - cd coder-gate
    - echo "Pipeline test started"
    - mvn verify
  artifacts: 
      paths:
        - ./coder-gate/target/surefire-reports
      reports:
        junit:
          - ./coder-gate/target/surefire-reports/TEST-*.xml
  tags:
    - Group19Runner

build-frontend:
  stage: build
  image: node:latest
  script:
    - cd coder-gate-ui
    - npm install
    - ng build --prod
  artifacts:
    paths:
      - ./coder-gate-ui/dist
  tags:
    - Group19Runner

build-backend:
  stage: build
  image: maven:latest
  script:
    - cd coder-gate
    - echo "Building the pipeline"
    - mvn clean package
  dependencies:
    - code_quality
    - test
    - build-frontend
  artifacts:
    paths:
      - coder-gate/target
      - coder-gate-ui/dist
  tags:
    - Group19Runner
