stages:
  - deploy

deploy-backend:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - 
    - ssh -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${DEPLOY_USER}@${DEPLOY_HOST} "cd ${DOCKER_BACK_END_PATH} && docker build -t coder-gate-backend:latest -f Dockerfile-backend ."
    - ssh -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${DEPLOY_USER}@${DEPLOY_HOST} "docker run -d --name coder-gate-backend -p 8080:8080 coder-gate-backend"
  tags:
    - Group19Runner
  only:
  - dev 

    
