stages:
  - test
  - code-Quality
  - build

include:
  - template: Code-Quality.gitlab-ci.yml

before_script:
   - apt-get update && apt-get install -y unzip

test:
  stage: test
  image: maven:latest
  artifacts: 
    paths:
      - coder-gate/target
    reports:
      junit:
        - ./coder-gate/target/ProjectReports/TEST_*.xml
  script:
    - cd coder-gate
    - echo "Pipeline test started"
    - mvn verify
  tags:
    - Group19Runner

code_quality:
  stage: code-Quality

  script: 
    - cd $CI_PROJECT_DIR
    - curl -L "https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.44.0/pmd-bin-6.44.0.zip" -o pmd.zip
    - unzip pmd.zip
    - ./pmd-bin-6.44.0/bin/run.sh pmd -d . -R java-basic,java-design -f json -r gl-code-quality-report.json # command to generate report
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - $CI_PROJECT_DIR/gl-code-quality-report.json # path to the report file
  tags:
    - Group19Runner


build:
  stage: build
  image: maven:latest
  script:
    - cd coder-gate
    - echo "Building the pipeline"
    - mvn clean package
  artifacts:
    paths:
      - coder-gate/target
  tags:
    - Group19Runner




