stages:
  - build
  - deploy


build-backend:
  stage: build
  image: maven:latest
  script:
    - cd coder-gate
    - echo "Building the pipeline"
    - mvn clean package
  artifacts:
    paths:
      - coder-gate/target
  tags:
    - Group19Runner

deploy-backend:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - ssh -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${DEPLOY_USER}@${DEPLOY_HOST} "sudo -S sh -c 'cd ${DOCKER_BACK_END_PATH} && docker build -t coder-gate-backend:latest -f Dockerfile-backend .'" < <(echo ${SUDO_PASSWORD})
    - ssh -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${DEPLOY_USER}@${DEPLOY_HOST} "docker run -d --name coder-gate-backend -p 80:80 coder-gate-backend"
  tags:
    - Group19Runner
  only:
  - dev 

    
